management:
  endpoints:
    web:
      exposure:
          include: info, health, bus-refresh, routes
          
server:
  port: ${port:5555}

spring:
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    fetch-registry: true
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE_URL:http://localhost:8761/eureka}
      
zuul:
  prefix: /api
